from pathlib import Path

worker = Path('trader/worker.py')
text = worker.read_text()
text = text.replace('ACTIVE_MARKET_COUNT = 20\nMIN_24H_QUOTE_VOLUME = Decimal(os.getenv("MIN_24H_QUOTE_VOLUME", "25000000"))\nMIN_24H_TRADES = int(os.getenv("MIN_24H_TRADES", "20000"))\nMAX_SPREAD_BPS = Decimal(os.getenv("MAX_SPREAD_BPS", "25"))', 'ACTIVE_MARKET_COUNT = 12\nMIN_24H_QUOTE_VOLUME = Decimal(os.getenv("MIN_24H_QUOTE_VOLUME", "5000000"))\nMIN_24H_TRADES = int(os.getenv("MIN_24H_TRADES", "5000"))\nMAX_SPREAD_BPS = Decimal(os.getenv("MAX_SPREAD_BPS", "20"))')
text = text.replace('def binance_account_summary(client: BinanceSpotClient, quote_asset: str) -> tuple[str, Decimal, Decimal]:', 'def binance_account_summary(client: BinanceSpotClient, quote_asset: str) -> tuple[str, Decimal, Decimal, str]:')
old = '''    total = Decimal("0")\n    invested = Decimal("0")\n    for asset, quantity in balances.items():\n        conversion = in_quote(asset)\n        if conversion is None:\n            continue\n        value = quantity * conversion\n        total += value\n        if asset != quote_asset:\n            invested += value\n    balance_text = ",".join(f"{asset}:{quantity}" for asset, quantity in balances.items()) or "none"\n    return balance_text, total, invested\n'''
new = '''    total = Decimal("0")\n    invested = Decimal("0")\n    wallet_values: dict[str, Decimal] = {}\n    for asset, quantity in balances.items():\n        conversion = in_quote(asset)\n        if conversion is None:\n            continue\n        value = quantity * conversion\n        wallet_values[asset] = value\n        total += value\n        if asset != quote_asset:\n            invested += value\n    balance_text = ",".join(f"{asset}:{quantity}" for asset, quantity in balances.items()) or "none"\n    wallet_value_text = ",".join(f"{asset}:{value}" for asset, value in wallet_values.items()) or "none"\n    return balance_text, total, invested, wallet_value_text\n'''
if old not in text:
    raise SystemExit('account summary block not found')
text = text.replace(old, new, 1)
text = text.replace('balances_text, account_total, invested_value = binance_account_summary(client, quote_asset)', 'balances_text, account_total, invested_value, wallet_value_text = binance_account_summary(client, quote_asset)')
text = text.replace('f"prices={price_text};balances={balances_text};account_total={account_total};invested_value={invested_value};markets=', 'f"prices={price_text};balances={balances_text};wallet_values={wallet_value_text};account_total={account_total};invested_value={invested_value};markets=')
worker.write_text(text)

dash = Path('app/trading-dashboard.tsx')
text = dash.read_text()
anchor = '''  const binanceBalances = useMemo(() => {\n    const balances = new Map<string, number>();\n    const match = lastEvent?.message.match(/(?:^|;)balances=([^;]+)/);\n    if (!match) return balances;\n    for (const item of match[1].split(",")) {\n      const [asset, rawQty] = item.split(":");\n      const qty = Number(rawQty);\n      if (asset && Number.isFinite(qty)) balances.set(asset, qty);\n    }\n    return balances;\n  }, [lastEvent]);\n\n'''
addition = anchor + '''  const binanceWalletValues = useMemo(() => {\n    const values = new Map<string, number>();\n    const match = lastEvent?.message.match(/(?:^|;)wallet_values=([^;]+)/);\n    if (!match) return values;\n    for (const item of match[1].split(",")) {\n      const [asset, rawValue] = item.split(":");\n      const value = Number(rawValue);\n      if (asset && Number.isFinite(value)) values.set(asset, value);\n    }\n    return values;\n  }, [lastEvent]);\n\n'''
if anchor not in text:
    raise SystemExit('balance parser anchor not found')
text = text.replace(anchor, addition, 1)
old_assets = '''    for (const symbol of marketPrices.keys()) if (symbol.endsWith(suffix)) names.add(symbol.slice(0, -suffix.length));\n    for (const trade of trades) if (trade.symbol.endsWith(suffix)) names.add(trade.symbol.slice(0, -suffix.length));\n    return Array.from(names);\n  }, [marketPrices, settings.quote_asset, trades]);\n'''
new_assets = '''    for (const symbol of marketPrices.keys()) if (symbol.endsWith(suffix)) names.add(symbol.slice(0, -suffix.length));\n    for (const trade of trades) if (trade.symbol.endsWith(suffix)) names.add(trade.symbol.slice(0, -suffix.length));\n    for (const [asset, value] of binanceWalletValues.entries()) if (asset !== suffix && value >= 5) names.add(asset);\n    return Array.from(names);\n  }, [marketPrices, settings.quote_asset, trades, binanceWalletValues]);\n'''
if old_assets not in text:
    raise SystemExit('assets block not found')
text = text.replace(old_assets, new_assets, 1)
old_alloc = '''    const walletQuantity = binanceBalances.has(asset) ? Number(binanceBalances.get(asset)) : quantity;\n    const authoritativeQuantity = walletQuantity * (marketPrices.get(symbol) ?? 0) >= 5 ? walletQuantity : 0;\n    const currentPrice = marketPrices.get(symbol) ?? null;\n    const currentValue = currentPrice === null ? null : authoritativeQuantity * currentPrice;\n    const adjustedInvested = quantity > 0 && authoritativeQuantity > 0 ? invested * Math.min(1, authoritativeQuantity / quantity) : 0;\n    const unrealized = currentValue === null ? null : currentValue - adjustedInvested;\n    return { asset, invested: adjustedInvested, quantity: authoritativeQuantity, pnl, currentPrice, currentValue, unrealized, owned: authoritativeQuantity > 0.000000001 };\n  }).sort((a, b) => Number(b.owned) - Number(a.owned) || MARKET_UNIVERSE.indexOf(a.asset as typeof MARKET_UNIVERSE[number]) - MARKET_UNIVERSE.indexOf(b.asset as typeof MARKET_UNIVERSE[number])), [assets, settings.quote_asset, trades, marketPrices, binanceBalances]);\n'''
new_alloc = '''    const walletQuantity = binanceBalances.has(asset) ? Number(binanceBalances.get(asset)) : quantity;\n    const walletValue = binanceWalletValues.get(asset);\n    const fallbackPrice = marketPrices.get(symbol) ?? null;\n    const resolvedValue = walletValue !== undefined ? walletValue : (fallbackPrice === null ? null : walletQuantity * fallbackPrice);\n    const owned = walletQuantity > 0.000000001 && resolvedValue !== null && resolvedValue >= 5;\n    const authoritativeQuantity = owned ? walletQuantity : 0;\n    const currentValue = owned ? resolvedValue : 0;\n    const currentPrice = authoritativeQuantity > 0 && currentValue !== null ? currentValue / authoritativeQuantity : fallbackPrice;\n    const adjustedInvested = quantity > 0 && authoritativeQuantity > 0 ? invested * Math.min(1, authoritativeQuantity / quantity) : 0;\n    const unrealized = currentValue === null ? null : currentValue - adjustedInvested;\n    return { asset, invested: adjustedInvested, quantity: authoritativeQuantity, pnl, currentPrice, currentValue, unrealized, owned };\n  }).sort((a, b) => Number(b.owned) - Number(a.owned) || Number(b.currentValue ?? 0) - Number(a.currentValue ?? 0) || MARKET_UNIVERSE.indexOf(a.asset as typeof MARKET_UNIVERSE[number]) - MARKET_UNIVERSE.indexOf(b.asset as typeof MARKET_UNIVERSE[number])), [assets, settings.quote_asset, trades, marketPrices, binanceBalances, binanceWalletValues]);\n'''
if old_alloc not in text:
    raise SystemExit('allocation block not found')
text = text.replace(old_alloc, new_alloc, 1)
dash.write_text(text)

Path('scripts/apply_wallet_marking_liquidity_tune.py').unlink(missing_ok=True)
Path('.github/workflows/apply-wallet-marking-liquidity-tune.yml').unlink(missing_ok=True)
