from pathlib import Path

worker = Path('trader/worker.py')
text = worker.read_text()
text = text.replace(
    'ACTIVE_MARKET_COUNT = 20\n',
    'ACTIVE_MARKET_COUNT = 20\nMIN_24H_QUOTE_VOLUME = Decimal(os.getenv("MIN_24H_QUOTE_VOLUME", "25000000"))\nMIN_24H_TRADES = int(os.getenv("MIN_24H_TRADES", "20000"))\nMAX_SPREAD_BPS = Decimal(os.getenv("MAX_SPREAD_BPS", "25"))\nBULLRUN_MAX_HOLD_SECONDS = int(os.getenv("BULLRUN_MAX_HOLD_SECONDS", "21600"))\n'
)
old_active = '''def active_pairs(client: BinanceSpotClient, quote_asset: str) -> tuple[str, ...]:\n    if quote_asset not in DEFAULT_CONFIG.preferred_quote_assets:\n        raise ValueError("Quote asset is outside the approved allowlist")\n    requested = {f"{asset}{quote_asset}" for asset in MARKET_UNIVERSE}\n    exchange_info = client._request("GET", "/api/v3/exchangeInfo")\n    available = {\n        item.get("symbol")\n        for item in exchange_info.get("symbols", [])\n        if item.get("symbol") in requested\n        and item.get("status") == "TRADING"\n        and item.get("quoteAsset") == quote_asset\n        and item.get("isSpotTradingAllowed", True)\n    }\n    tickers = client._request("GET", "/api/v3/ticker/24hr")\n    quote_volume = {\n        item.get("symbol"): Decimal(str(item.get("quoteVolume", "0")))\n        for item in tickers\n        if item.get("symbol") in available\n    }\n    ordered = sorted(available, key=lambda symbol: quote_volume.get(symbol, Decimal("0")), reverse=True)\n    selected = tuple(ordered[:ACTIVE_MARKET_COUNT])\n    if not selected:\n        raise BinanceError(f"No approved {quote_asset} spot pairs are currently available")\n    return selected\n'''
new_active = '''def ticker_is_liquid(item: dict[str, object]) -> bool:\n    quote_volume = Decimal(str(item.get("quoteVolume", "0")))\n    trades = int(item.get("count", 0) or 0)\n    bid = Decimal(str(item.get("bidPrice", "0")))\n    ask = Decimal(str(item.get("askPrice", "0")))\n    if quote_volume < MIN_24H_QUOTE_VOLUME or trades < MIN_24H_TRADES or bid <= 0 or ask <= 0 or ask < bid:\n        return False\n    mid = (bid + ask) / Decimal("2")\n    spread_bps = ((ask - bid) / mid) * Decimal("10000") if mid > 0 else Decimal("999999")\n    return spread_bps <= MAX_SPREAD_BPS\n\n\ndef active_pairs(client: BinanceSpotClient, quote_asset: str) -> tuple[str, ...]:\n    if quote_asset not in DEFAULT_CONFIG.preferred_quote_assets:\n        raise ValueError("Quote asset is outside the approved allowlist")\n    requested = {f"{asset}{quote_asset}" for asset in MARKET_UNIVERSE}\n    exchange_info = client._request("GET", "/api/v3/exchangeInfo")\n    available = {\n        item.get("symbol")\n        for item in exchange_info.get("symbols", [])\n        if item.get("symbol") in requested\n        and item.get("status") == "TRADING"\n        and item.get("quoteAsset") == quote_asset\n        and item.get("isSpotTradingAllowed", True)\n    }\n    tickers = client._request("GET", "/api/v3/ticker/24hr")\n    eligible = [item for item in tickers if item.get("symbol") in available and ticker_is_liquid(item)]\n    ordered = sorted(\n        eligible,\n        key=lambda item: (Decimal(str(item.get("quoteVolume", "0"))), int(item.get("count", 0) or 0)),\n        reverse=True,\n    )\n    selected = tuple(str(item.get("symbol")) for item in ordered[:ACTIVE_MARKET_COUNT])\n    if not selected:\n        raise BinanceError(\n            f"No approved {quote_asset} spot pairs meet liquidity requirements "\n            f"(volume>={MIN_24H_QUOTE_VOLUME}, trades>={MIN_24H_TRADES}, spread<={MAX_SPREAD_BPS}bps)"\n        )\n    return selected\n'''
if old_active not in text:
    raise SystemExit('active_pairs block not found')
text = text.replace(old_active, new_active, 1)

anchor = '''def market_scan(\n'''
helpers = '''def bullrun_candidate(analysis: MarketAnalysis, scalp: ScalpAnalysis, risk_profile: str) -> bool:\n    return (\n        risk_profile in {"normal", "high"}\n        and analysis.score >= 7\n        and analysis.volume_ratio_15m >= Decimal("1.25")\n        and Decimal("0.35") <= analysis.atr_percent_1h <= Decimal("6")\n        and scalp.score >= 4\n        and "risk_veto" not in analysis.reasons\n    )\n\n\ndef bullrun_profile(analysis: MarketAnalysis, configured_stop_percent: object, risk_profile: str) -> tuple[Decimal, Decimal, Decimal]:\n    configured = Decimal(str(configured_stop_percent or "1")) / Decimal("100")\n    atr_fraction = analysis.atr_percent_1h / Decimal("100")\n    stop = min(Decimal("0.03"), max(configured, atr_fraction * Decimal("1.5")))\n    activation = min(Decimal("0.05"), max(Decimal("0.02"), stop * Decimal("1.25")))\n    size_multiplier = Decimal("1.50") if risk_profile == "high" else Decimal("1.25")\n    return stop, activation, size_multiplier\n\n\n'''
if anchor not in text:
    raise SystemExit('market_scan anchor not found')
text = text.replace(anchor, helpers + anchor, 1)

old_rank = '''    ranked = sorted(\n        pairs,\n        key=lambda pair: (\n            1 if scalp_enabled and scalp_analyses[pair].signal else 0,\n            scalp_analyses[pair].score,\n            analyses[pair].score,\n        ),\n        reverse=True,\n    )\n\n    signals: dict[str, bool] = {}\n    strategies: dict[str, str] = {}\n    for pair in ranked:\n        swing_signal = (\n            analyses[pair].score >= swing_threshold\n            and "risk_veto" not in analyses[pair].reasons\n            and not blocked_by_news\n        )\n        scalp_signal = scalp_enabled and scalp_analyses[pair].signal and not blocked_by_news\n        signals[pair] = scalp_signal or swing_signal\n        strategies[pair] = "scalp" if scalp_signal else "swing"\n\n    scalp_signal_text = ",".join(pair for pair in ranked if scalp_enabled and scalp_analyses[pair].signal) or "none"\n    context = (\n        f"threshold={swing_threshold};risk={risk_profile};btc_regime={btc_regime};"\n        f"news={news.score:.2f};headlines={news.fresh_headlines};scalp={scalp_signal_text}"\n    )\n'''
new_rank = '''    bullruns = {pair: bullrun_candidate(analyses[pair], scalp_analyses[pair], risk_profile) for pair in pairs}\n    ranked = sorted(\n        pairs,\n        key=lambda pair: (\n            2 if bullruns[pair] else (1 if scalp_enabled and scalp_analyses[pair].signal else 0),\n            scalp_analyses[pair].score,\n            analyses[pair].score,\n            analyses[pair].volume_ratio_15m,\n        ),\n        reverse=True,\n    )\n\n    signals: dict[str, bool] = {}\n    strategies: dict[str, str] = {}\n    for pair in ranked:\n        swing_signal = (\n            analyses[pair].score >= swing_threshold\n            and "risk_veto" not in analyses[pair].reasons\n            and not blocked_by_news\n        )\n        scalp_signal = scalp_enabled and scalp_analyses[pair].signal and not blocked_by_news\n        bullrun_signal = bullruns[pair] and not blocked_by_news\n        signals[pair] = bullrun_signal or scalp_signal or swing_signal\n        strategies[pair] = "bullrun" if bullrun_signal else ("scalp" if scalp_signal else "swing")\n\n    scalp_signal_text = ",".join(pair for pair in ranked if scalp_enabled and scalp_analyses[pair].signal) or "none"\n    bullrun_text = ",".join(pair for pair in ranked if bullruns[pair]) or "none"\n    context = (\n        f"threshold={swing_threshold};risk={risk_profile};btc_regime={btc_regime};"\n        f"news={news.score:.2f};headlines={news.fresh_headlines};scalp={scalp_signal_text};bullrun={bullrun_text}"\n    )\n'''
if old_rank not in text:
    raise SystemExit('market ranking block not found')
text = text.replace(old_rank, new_rank, 1)

old_call = '''            result = run_portfolio_cycle(\n                client,\n                signals,\n                state_path,\n                PortfolioLimits.from_settings(runtime_settings) if settings else PortfolioLimits.from_env(),\n                reporter.record_trade if reporter else None,\n                allow_new_entries=allow_new_entries,\n                quote_asset=quote_asset,\n                entry_strategies=strategies,\n            )\n'''
new_call = '''            stop_overrides: dict[str, Decimal] = {}\n            activation_overrides: dict[str, Decimal] = {}\n            size_multipliers: dict[str, Decimal] = {}\n            max_hold_overrides: dict[str, int] = {}\n            for pair, strategy in strategies.items():\n                if strategy == "bullrun":\n                    stop, activation, size_multiplier = bullrun_profile(\n                        analyses[pair], (settings or {}).get("stop_loss_percent", "1"), risk_profile\n                    )\n                    stop_overrides[pair] = stop\n                    activation_overrides[pair] = activation\n                    size_multipliers[pair] = size_multiplier\n                    max_hold_overrides[pair] = BULLRUN_MAX_HOLD_SECONDS\n\n            result = run_portfolio_cycle(\n                client,\n                signals,\n                state_path,\n                PortfolioLimits.from_settings(runtime_settings) if settings else PortfolioLimits.from_env(),\n                reporter.record_trade if reporter else None,\n                allow_new_entries=allow_new_entries,\n                quote_asset=quote_asset,\n                entry_strategies=strategies,\n                entry_stop_fractions=stop_overrides,\n                entry_target_fractions=activation_overrides,\n                entry_size_multipliers=size_multipliers,\n                entry_max_hold_seconds=max_hold_overrides,\n            )\n'''
if old_call not in text:
    raise SystemExit('portfolio call block not found')
text = text.replace(old_call, new_call, 1)
worker.write_text(text)

portfolio = Path('trader/portfolio_live.py')
text = portfolio.read_text()
old_sig = '''    quote_asset: str = "USDC",\n    entry_strategies: dict[str, str] | None = None,\n) -> str:\n'''
new_sig = '''    quote_asset: str = "USDC",\n    entry_strategies: dict[str, str] | None = None,\n    entry_stop_fractions: dict[str, Decimal] | None = None,\n    entry_target_fractions: dict[str, Decimal] | None = None,\n    entry_size_multipliers: dict[str, Decimal] | None = None,\n    entry_max_hold_seconds: dict[str, int] | None = None,\n) -> str:\n'''
if old_sig not in text:
    raise SystemExit('portfolio signature block not found')
text = text.replace(old_sig, new_sig, 1)
old_strategy = '''    strategy = (entry_strategies or {}).get(symbol, "swing")\n    if strategy == "scalp":\n        stop_fraction, activation_fraction, max_hold = SCALP_STOP_FRACTION, SCALP_TARGET_FRACTION, SCALP_MAX_HOLD_SECONDS\n    else:\n        stop_fraction, activation_fraction, max_hold = limits.stop_fraction, limits.target_fraction, None\n\n    spend = min(limits.order_size, free_quote)\n'''
new_strategy = '''    strategy = (entry_strategies or {}).get(symbol, "swing")\n    if strategy == "scalp":\n        stop_fraction, activation_fraction, max_hold = SCALP_STOP_FRACTION, SCALP_TARGET_FRACTION, SCALP_MAX_HOLD_SECONDS\n    else:\n        stop_fraction = (entry_stop_fractions or {}).get(symbol, limits.stop_fraction)\n        activation_fraction = (entry_target_fractions or {}).get(symbol, limits.target_fraction)\n        max_hold = (entry_max_hold_seconds or {}).get(symbol)\n\n    multiplier = max(Decimal("0.5"), min(Decimal("1.5"), Decimal(str((entry_size_multipliers or {}).get(symbol, Decimal("1"))))))\n    max_fraction_of_free = Decimal("0.35")\n    spend = min(limits.order_size * multiplier, free_quote * max_fraction_of_free, free_quote)\n    if spend < Decimal("5"):\n        return f"insufficient_{quote.lower()}_for_sized_entry"\n'''
if old_strategy not in text:
    raise SystemExit('strategy sizing block not found')
text = text.replace(old_strategy, new_strategy, 1)
portfolio.write_text(text)

Path('tests/test_market_brain_v2.py').write_text('''import unittest\nfrom decimal import Decimal\n\nfrom trader.analysis import MarketAnalysis\nfrom trader.scalping import ScalpAnalysis\nfrom trader.worker import bullrun_candidate, bullrun_profile, ticker_is_liquid\n\n\nclass MarketBrainV2Tests(unittest.TestCase):\n    def test_liquidity_gate_requires_volume_trades_and_tight_spread(self):\n        good = {"quoteVolume": "50000000", "count": 50000, "bidPrice": "100", "askPrice": "100.10"}\n        thin = {"quoteVolume": "1000000", "count": 500, "bidPrice": "100", "askPrice": "101"}\n        self.assertTrue(ticker_is_liquid(good))\n        self.assertFalse(ticker_is_liquid(thin))\n\n    def test_bullrun_requires_multitimeframe_strength_and_volume(self):\n        analysis = MarketAnalysis(True, 8, Decimal("0.88"), Decimal("62"), Decimal("1.4"), Decimal("1.6"), ("15m_trend","1h_trend","4h_trend","volume_confirmation"))\n        scalp = ScalpAnalysis(True, 6, Decimal("0.01"), Decimal("0.02"), Decimal("1.4"), ("1m_fast_trend",))\n        self.assertTrue(bullrun_candidate(analysis, scalp, "high"))\n        weak = MarketAnalysis(True, 8, Decimal("0.88"), Decimal("62"), Decimal("1.4"), Decimal("1.0"), ("15m_trend",))\n        self.assertFalse(bullrun_candidate(weak, scalp, "high"))\n\n    def test_bullrun_profile_is_wider_but_bounded(self):\n        analysis = MarketAnalysis(True, 8, Decimal("0.88"), Decimal("62"), Decimal("1.5"), Decimal("1.6"), ())\n        stop, activation, multiplier = bullrun_profile(analysis, "1.5", "high")\n        self.assertEqual(stop, Decimal("0.0225"))\n        self.assertEqual(activation, Decimal("0.028125"))\n        self.assertEqual(multiplier, Decimal("1.50"))\n\n\nif __name__ == "__main__":\n    unittest.main()\n''')

Path('scripts/apply_market_brain_v2.py').unlink(missing_ok=True)
Path('.github/workflows/apply-market-brain-v2.yml').unlink(missing_ok=True)
