-- Additive reconstruction from the checked-in dashboard/worker API contract.
-- This prepares storage, NOT historical data or restored exchange access.
-- Client writes remain revoked until recovery, MFA and credential RPCs exist.
create table public.bot_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  bot_enabled boolean not null default false,
  live_trading_enabled boolean not null default false,
  risk_profile text not null default 'normal' check (risk_profile in ('low','normal','high','extreme')),
  quote_asset text not null default 'USDC' check (quote_asset in ('USDC','USDT')),
  trade_cap_usdc numeric not null default 100 check (trade_cap_usdc > 0),
  order_size_usdc numeric not null default 25 check (order_size_usdc > 0),
  stop_loss_percent numeric not null default 1 check (stop_loss_percent > 0),
  take_profit_percent numeric not null default 2 check (take_profit_percent > 0),
  max_daily_loss_usdc numeric not null default 2 check (max_daily_loss_usdc > 0),
  short_enabled boolean not null default false,
  futures_enabled boolean not null default false,
  leverage integer not null default 1 check (leverage between 1 and 20),
  daily_loss_reset_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.trades (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null check (symbol ~ '^[A-Z0-9]{3,24}$'),
  mode text not null default 'live' check (mode in ('paper','live','margin','futures')),
  side text not null check (side in ('BUY','SELL')),
  quantity numeric not null check (quantity > 0),
  entry_price numeric,
  exit_price numeric,
  pnl numeric,
  leverage integer default 1 check (leverage between 1 and 20),
  created_at timestamptz not null default now()
);
create index trades_user_created on public.trades (user_id, created_at desc);
create table public.bot_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  level text not null default 'info' check (level in ('info','warning','error')),
  event_type text not null,
  message text not null,
  created_at timestamptz not null default now()
);
create index bot_events_user_type_created on public.bot_events (user_id,event_type,created_at desc);
create table public.trade_directives (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null check (symbol ~ '^[A-Z0-9]{3,24}$'),
  direction text not null check (direction in ('LONG','SHORT')),
  mode text not null check (mode in ('SPOT','MARGIN','FUTURES')),
  requested_notional numeric not null check (requested_notional >= 5),
  leverage integer not null default 1 check (leverage between 1 and 20),
  status text not null default 'pending' check (status in ('pending','executed','rejected','expired','cancelled')),
  result text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '15 minutes'),
  handled_at timestamptz
);
create index trade_directives_user_pending on public.trade_directives(user_id,created_at desc) where status='pending';
create table public.user_access (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  approved boolean not null default false,
  rejected boolean not null default false,
  is_admin boolean not null default false,
  approved_at timestamptz,
  approved_by uuid,
  rejected_at timestamptz,
  rejected_by uuid,
  created_at timestamptz not null default now(),
  check (not (approved and rejected))
);
-- Raw recovery evidence is never a public dashboard table or a trade ledger.
-- Only server credentials can read or write it. No secrets belong in payload.
create table public.trading_recovery_uploads (
  id uuid primary key default gen_random_uuid(),
  legacy_user_id uuid not null,
  payload jsonb not null check (jsonb_typeof(payload)='object'),
  created_at timestamptz not null default now()
);
create index recovery_uploads_legacy_created on public.trading_recovery_uploads(legacy_user_id,created_at desc);

do $block$
declare t text;
begin
  foreach t in array array['bot_settings','trades','bot_events','trade_directives','user_access','trading_recovery_uploads'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from public, anon, authenticated', t);
    execute format('grant all on table public.%I to service_role', t);
    if t <> 'trading_recovery_uploads' then
      execute format('grant select on table public.%I to authenticated', t);
      execute format($policy$
        create policy trading_own_member_read on public.%I for select to authenticated
        using (user_id = (select auth.uid()) and exists (
          select 1 from public.internal_app_memberships m
          join public.internal_apps a on a.id=m.app_id
          where m.user_id=(select auth.uid()) and a.slug='ai-trading-app'
        ))
      $policy$, t);
    end if;
  end loop;
end;
$block$;
revoke all on sequence public.trades_id_seq,public.bot_events_id_seq,public.trade_directives_id_seq from public,anon,authenticated;
grant usage,select on sequence public.trades_id_seq,public.bot_events_id_seq,public.trade_directives_id_seq to service_role;

create function trading_auth.provision_trading_storage() returns trigger
language plpgsql security definer set search_path='' as $function$
begin
  if not exists(select 1 from public.internal_apps a where a.id=new.app_id and a.slug='ai-trading-app') then
    return new;
  end if;
  insert into public.bot_settings(user_id) values(new.user_id) on conflict do nothing;
  insert into public.user_access(user_id,email,approved,is_admin,approved_at)
    select u.id,u.email,true,new.role='admin',now() from auth.users u where u.id=new.user_id
    on conflict(user_id) do update set approved=true,rejected=false,is_admin=excluded.is_admin;
  return new;
end;
$function$;
revoke all on function trading_auth.provision_trading_storage() from public,anon,authenticated;
create trigger provision_trading_storage after insert or update of role
on public.internal_app_memberships for each row execute function trading_auth.provision_trading_storage();

insert into public.bot_settings(user_id)
select m.user_id from public.internal_app_memberships m join public.internal_apps a on a.id=m.app_id
where a.slug='ai-trading-app' on conflict do nothing;
insert into public.user_access(user_id,email,approved,is_admin,approved_at)
select u.id,u.email,true,m.role='admin',now()
from public.internal_app_memberships m join public.internal_apps a on a.id=m.app_id join auth.users u on u.id=m.user_id
where a.slug='ai-trading-app' on conflict do nothing;
notify pgrst, 'reload schema';
